name: SketchCloud
favicon: null
layout_spectrum: 0
typography_spectrum: 0.6331253482494503
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8297064155340195
  lightness: 0.3341356609016657
  saturation: 0.550768302520737
  rhythmicContrast: 0.6704625727143139
purpose: []
