analytics: {}
color:
  brandColors:
    - '#98B8C8'
    - '#104858'
    - '#688090'
    - '#E8C838'
    - '#E8E048'
  brandStrength: 1
  lightness: 0.38429
  rhythmicContrast: 0.65625
  saturation: 0.663006
cta: {}
layout_spectrum: 1
name: SketchCloud
opengraph: {}
purpose: []
typography_spectrum: 0.60304
