name: SketchCloud
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60304
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#98B8C8'
    - '#104858'
    - '#688090'
    - '#E8C838'
    - '#E8E048'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
