analytics: {}
color:
  brandColors:
    - '#000000'
  brandStrength: 1
  lightness: 0.3341356609016657
  rhythmicContrast: 0.6704625727143139
  saturation: 0.550768302520737
cta: {}
layout_spectrum: 0.200168
name: SketchCloud
opengraph: {}
purpose: []
typography_spectrum: 0.60304
