analytics: {}
color:
  brandColors:
    - '#98B8C8'
    - '#104858'
    - '#688090'
    - '#E8C838'
    - '#E8E048'
  brandStrength: 0.650337
  lightness: 0.501689
  rhythmicContrast: 0.494932
  saturation: 0.522804
cta: {}
layout_spectrum: 0.590371
name: SketchCloud
opengraph: {}
purpose: []
typography_spectrum: 0.60304
